centos5:
  dockerfile: Dockerfile.centos5
  build: .
  command: cp -a /usr/local/src/cmogstored-1.6.0/cmogstored /tmp/cmogstored.centos5
  volumes:
    - .:/tmp:rw

centos6:
  dockerfile: Dockerfile.centos6
  build: .
  command: cp -a /usr/local/src/cmogstored-1.6.0/cmogstored /tmp/cmogstored.centos6
  volumes:
    - .:/tmp:rw

centos7:
  dockerfile: Dockerfile.centos7
  build: .
  command: cp -a /usr/local/src/cmogstored-1.6.0/cmogstored /tmp/cmogstored.centos7
  volumes:
    - .:/tmp:rw

ubuntu1404:
  dockerfile: Dockerfile.ubuntu1404
  build: .
  command: cp -a /usr/local/src/cmogstored-1.6.0/cmogstored /tmp/cmogstored.ubuntu1404
  volumes:
    - .:/tmp:rw

ubuntu1504:
  dockerfile: Dockerfile.ubuntu1504
  build: .
  command: cp -a /usr/local/src/cmogstored-1.6.0/cmogstored /tmp/cmogstored.ubuntu1504
  volumes:
    - .:/tmp:rw
